import 'zone.js';
import { bootstrapApplication } from '@angular/platform-browser';
import { Component, AfterViewInit, OnDestroy, ElementRef } from '@angular/core';
import { FormsModule } from '@angular/forms';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';

gsap.registerPlugin(ScrollTrigger);
@Component({selector:'app-root',standalone:true,imports:[FormsModule],host:{'(document:keydown.escape)':'closeBooking()'},template:`
<div class="progress" aria-hidden="true"></div>
<header><a class="brand" href="#inicio" aria-label="Altior início">ALTIOR<span>BARBEARIA</span></a><nav><a href="#essencia">A essência</a><a href="#rituais">Os rituais</a><a href="#espaco">O espaço</a></nav><button class="book small" (click)="openBooking()">Reserve seu momento <span>↗</span></button></header>
<main>
<section class="hero" id="inicio"><div class="hero-top"><span>PRECISÃO NO CORTE. PRESENÇA NO MUNDO.</span><span>ESTILO É IDENTIDADE — ALTIOR</span></div><div class="hero-title"><h1>Seu estilo,<br><em>elevado.</em></h1><div class="hero-note"><span class="asterisk">✳</span><p>Mais que um corte.<br>Um novo jeito de se sentir.</p></div></div><div class="hero-photo"><img src="https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=2200&q=85" alt="Barbeiro trabalhando com precisão em um corte masculino" fetchpriority="high"><div class="photo-shade"></div><div class="photo-caption"><span>O SEU PRÓXIMO CAPÍTULO<br>COMEÇA NA NOSSA CADEIRA.</span><button class="circle" (click)="openBooking()" aria-label="Planejar uma visita">↗</button></div><a class="scroll-label" href="#essencia">EXPLORE A ALTIOR <span>↓</span></a></div><div class="hero-bottom"><span>BARBEARIA CONTEMPORÂNEA</span><span>FEITO PARA VOCÊ. NOS MÍNIMOS DETALHES.</span><span>01 / 04</span></div></section>
<section class="essence section" id="essencia"><div class="eyebrow"><span>01 — A NOSSA ESSÊNCIA</span><span>O CUIDADO MUDA TUDO.</span></div><div class="manifesto"><h2 class="reveal">Não é só sobre<br>como você <em>parece.</em><br>É sobre como<br>você <em>se sente.</em></h2><div class="essence-copy"><span class="asterisk">✳</span><p>Existe uma versão sua que chega antes de qualquer palavra. Está na postura, na confiança, nos detalhes.</p><p>Na Altior, cada corte é um encontro entre técnica e personalidade. Um tempo para desacelerar. Um cuidado para levar com você.</p><a class="text-link" href="#rituais">Conheça nossos rituais <span>↗</span></a></div></div></section>
<div class="marquee" aria-hidden="true"><div>ESTILO COM PROPÓSITO <span>✳</span> CUIDADO COM PRESENÇA <span>✳</span> ESTILO COM PROPÓSITO <span>✳</span> CUIDADO COM PRESENÇA <span>✳</span></div></div>
<section class="rituals section" id="rituais"><div class="eyebrow"><span>02 — OS RITUAIS</span><span>TÉCNICA. TEMPO. ATENÇÃO.</span></div><div class="section-heading"><h2 class="reveal">O detalhe faz<br><em>a diferença.</em></h2><p>Escolha seu ritual.<br>O resto, deixa com a gente.</p></div><div class="service-list">@for(service of services; track service.name; let i = $index){<button class="service" (click)="openBooking(service.name)"><span class="number">0{{i+1}}</span><div><h3>{{service.name}}</h3><p>{{service.description}}</p></div><span class="service-tag">{{service.tag}}</span><span class="service-arrow">↗</span></button>}</div><p class="service-footnote">Valores e duração: consulte a equipe ao planejar sua visita.</p></section>
<section class="space" id="espaco"><div class="section space-intro"><div class="eyebrow"><span>03 — O UNIVERSO ALTIOR</span><span>DESACELERE. VOCÊ CHEGOU.</span></div><h2 class="reveal">Seu tempo.<br><em>Seu lugar.</em></h2><p>Uma pausa na rotina.<br>Uma experiência em cada detalhe.</p></div><div class="gallery-track"><figure><img src="https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1400&q=85" alt="Referência visual de atendimento em barbearia" loading="lazy"><figcaption><span>01 / O RITUAL</span><span>ATENÇÃO EM CADA GESTO</span></figcaption></figure><figure><img src="https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=85" alt="Referência visual de cuidado com cabelo masculino" loading="lazy"><figcaption><span>02 / A TÉCNICA</span><span>PERSONALIDADE EM CADA CORTE</span></figcaption></figure><figure class="quote-card"><span>✳</span><blockquote>O melhor<br>do seu estilo.<br><em>Todos os dias.</em></blockquote><small>ESSA É A NOSSA ESSÊNCIA.</small></figure></div><span class="gallery-hint">CONTINUE EXPLORANDO →</span></section>
<section class="visit section" id="visita"><div class="eyebrow"><span>04 — SEU PRÓXIMO MOMENTO</span><span>VAMOS ELEVAR SEU ESTILO.</span></div><div class="visit-main"><h2 class="reveal">A cadeira<br>é <em>sua.</em></h2><button class="visit-button" (click)="openBooking()"><span>Planeje sua visita</span><span>↗</span></button></div><div class="visit-bottom"><p>Converse com a Altior para consultar<br>serviços, horários e disponibilidade.</p><a href="https://www.instagram.com/altiorbarbearia/" target="_blank" rel="noopener noreferrer">&#64;altiorbarbearia ↗</a></div></section>
</main><footer><a class="footer-logo" href="#inicio">ALTIOR<span>✳</span></a><div><span>SEU ESTILO, ELEVADO.</span><span>© {{year}} ALTIOR BARBEARIA</span><a href="#inicio">VOLTAR AO TOPO ↑</a></div><p class="prototype-note">Conceito visual · Fotografias de referência · Agendamento sujeito à confirmação da equipe.</p></footer>
@if(bookingOpen){<div class="modal-backdrop" (click)="closeBooking()"><section class="booking-dialog" role="dialog" aria-modal="true" aria-labelledby="booking-title" (click)="$event.stopPropagation()"><button class="close" (click)="closeBooking()" aria-label="Fechar">×</button><span class="eyebrow">SEU MOMENTO ALTIOR</span><h2 id="booking-title">Vamos cuidar<br>do seu <em>estilo.</em></h2><p>Prepare sua solicitação e envie à equipe pelo Instagram. A reserva depende da confirmação da barbearia.</p><form (ngSubmit)="prepareRequest()"><label>Seu nome<input name="name" [(ngModel)]="name" required autocomplete="given-name" placeholder="Como podemos chamar você?"></label><label>Seu ritual<select name="service" [(ngModel)]="selectedService">@for(service of services; track service.name){<option>{{service.name}}</option>}</select></label><label>Data desejada<input name="date" type="date" [(ngModel)]="date" [min]="today" required></label><button class="submit" type="submit">Preparar solicitação <span>↗</span></button></form>@if(request){<div class="request"><p>{{request}}</p><button (click)="copyRequest()">{{copied ? 'Mensagem copiada ✓' : 'Copiar mensagem'}}</button><a href="https://www.instagram.com/altiorbarbearia/" target="_blank" rel="noopener noreferrer">Abrir Instagram ↗</a><small>Copie a mensagem e envie por Direct para consultar disponibilidade.</small></div>}</section></div>}
`})
export class App implements AfterViewInit, OnDestroy {
 year=new Date().getFullYear(); today=new Date().toLocaleDateString('en-CA'); bookingOpen=false; name=''; date=''; selectedService='Corte'; request=''; copied=false;
 services=[{name:'Corte',description:'Seu estilo traduzido em forma, textura e precisão.',tag:'IDENTIDADE'},{name:'Barba',description:'Desenho, alinhamento e cuidado em cada detalhe.',tag:'PRESENÇA'},{name:'Corte + barba',description:'Uma experiência completa. Um visual em harmonia.',tag:'O RITUAL COMPLETO'}];
 private lenis?:Lenis; private context?:gsap.Context; private tick?:(time:number)=>void;
 constructor(private element:ElementRef){}
 ngAfterViewInit(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return; this.lenis=new Lenis({duration:1.2,anchors:true});this.lenis.on('scroll',ScrollTrigger.update);this.tick=(time)=>this.lenis?.raf(time*1000);gsap.ticker.add(this.tick);this.context=gsap.context(()=>{gsap.from('.hero-title h1',{y:90,opacity:0,duration:1.4,ease:'power3.out'});gsap.from('.hero-note',{y:30,opacity:0,duration:1,delay:.4});gsap.to('.progress',{scaleX:1,ease:'none',scrollTrigger:{trigger:'main',start:'top top',end:'bottom bottom',scrub:true}});gsap.to('.hero-photo img',{yPercent:16,ease:'none',scrollTrigger:{trigger:'.hero-photo',start:'top top',end:'bottom top',scrub:true}});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:65,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%'}}));gsap.utils.toArray<HTMLElement>('.service').forEach(el=>gsap.from(el,{y:35,opacity:0,duration:.7,scrollTrigger:{trigger:el,start:'top 92%'}}));ScrollTrigger.matchMedia({'(min-width: 900px)':()=>{const track=this.element.nativeElement.querySelector('.gallery-track') as HTMLElement;gsap.to(track,{x:()=>-Math.max(0,track.scrollWidth-window.innerWidth+80),ease:'none',scrollTrigger:{trigger:'.space',start:'top top',end:()=>'+='+window.innerWidth,pin:true,scrub:1,invalidateOnRefresh:true}})}});},this.element.nativeElement);}
 openBooking(service='Corte'){this.selectedService=service;this.bookingOpen=true;this.request='';this.copied=false;this.lenis?.stop();document.body.style.overflow='hidden';setTimeout(()=>this.element.nativeElement.querySelector('.close')?.focus());}
 closeBooking(){this.bookingOpen=false;this.lenis?.start();document.body.style.overflow='';}
 prepareRequest(){if(!this.name.trim()||!this.date)return;const date=this.date.split('-').reverse().join('/');this.request='Olá, Altior! Sou '+this.name.trim()+'. Gostaria de consultar disponibilidade para '+this.selectedService.toLowerCase()+' no dia '+date+'. Quais horários e valores estão disponíveis?';}
 async copyRequest(){try{await navigator.clipboard.writeText(this.request);this.copied=true;}catch{this.copied=false;}}
 ngOnDestroy(){this.context?.revert();if(this.tick)gsap.ticker.remove(this.tick);this.lenis?.destroy();document.body.style.overflow='';}
}
bootstrapApplication(App).catch(console.error);

